import React, { useState } from 'react';
import { Project, MissingInfoItem } from '../../types';
import { generateMissingInfoChecklist } from '../../utils/analysisEngine';
import { 
  AlertTriangle, 
  CheckCircle2, 
  HelpCircle, 
  Plus, 
  FileCheck, 
  ExternalLink,
  ShieldCheck,
  Send,
  MessageSquare
} from 'lucide-react';

interface MissingInfoViewProps {
  project: Project;
  onUpdateProject: (updated: Project) => void;
}

export const MissingInfoView: React.FC<MissingInfoViewProps> = ({
  project,
  onUpdateProject
}) => {
  // Combine auto-generated missing info with stored project missing info
  const autoGenerated = generateMissingInfoChecklist(project);
  const currentMissingList = project.missingInformation.length > 0 ? project.missingInformation : autoGenerated;

  const [items, setItems] = useState<MissingInfoItem[]>(currentMissingList);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // New item modal
  const [isAddingItem, setIsAddingItem] = useState(false);
  const [newItemTitle, setNewItemTitle] = useState('');
  const [newItemCategory, setNewItemCategory] = useState<MissingInfoItem['category']>('VERROU');
  const [newItemQuestion, setNewItemQuestion] = useState('');
  const [newItemDeliverable, setNewItemDeliverable] = useState('');

  const toggleResolved = (id: string) => {
    const updated = items.map(item => item.id === id ? { ...item, resolved: !item.resolved } : item);
    setItems(updated);
    onUpdateProject({ ...project, missingInformation: updated });
  };

  const handleCopyQuestion = (id: string, question: string) => {
    navigator.clipboard.writeText(question);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleAddNewItem = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newItemTitle) return;

    const created: MissingInfoItem = {
      id: `miss-custom-${Date.now()}`,
      category: newItemCategory,
      title: newItemTitle,
      description: 'Élément additionnel identifié par le consultant en audit.',
      impactOnAudit: 'Sécurisation de la justification technique en cas de demande d’informations de l’administration.',
      recommendedQuestion: newItemQuestion || 'Pouvez-vous préciser ce point pour consolider le dossier ?',
      expectedDeliverable: newItemDeliverable || 'Note technique ou document justificatif.',
      resolved: false
    };

    const updated = [created, ...items];
    setItems(updated);
    onUpdateProject({ ...project, missingInformation: updated });
    setIsAddingItem(false);
    setNewItemTitle('');
    setNewItemQuestion('');
    setNewItemDeliverable('');
  };

  const unresolvedCount = items.filter(i => !i.resolved).length;

  const getCategoryBadge = (cat: MissingInfoItem['category']) => {
    switch (cat) {
      case 'ETAT_DE_LART':
        return <span className="bg-blue-50 text-blue-700 px-2 py-0.5 rounded text-[10px] font-semibold border border-blue-200">État de l’art</span>;
      case 'VERROU':
        return <span className="bg-red-50 text-red-700 px-2 py-0.5 rounded text-[10px] font-semibold border border-red-200">Verrou technique</span>;
      case 'EXPERIMENTATION':
        return <span className="bg-purple-50 text-purple-700 px-2 py-0.5 rounded text-[10px] font-semibold border border-purple-200">Expérimentation</span>;
      case 'RESULTATS':
        return <span className="bg-emerald-50 text-emerald-700 px-2 py-0.5 rounded text-[10px] font-semibold border border-emerald-200">Résultats chiffrés</span>;
      case 'PERSONNEL':
        return <span className="bg-orange-50 text-orange-700 px-2 py-0.5 rounded text-[10px] font-semibold border border-orange-200">Personnel R&D</span>;
      case 'CII_MARCHE':
        return <span className="bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded text-[10px] font-semibold border border-indigo-200">Marché CII</span>;
      default:
        return <span className="bg-slate-50 text-slate-700 px-2 py-0.5 rounded text-[10px] font-semibold border border-slate-200">Général</span>;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-semibold text-amber-700 uppercase tracking-wider mb-1">
            <AlertTriangle className="w-4 h-4 text-amber-600" />
            Sécurisation du Contrôle Fiscal & MESR
          </div>
          <h2 className="text-base font-bold text-slate-900 tracking-tight">
            Informations nécessaires pour sécuriser l’analyse
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Projet : <strong className="text-slate-800">{project.name}</strong> · {unresolvedCount} élément(s) prioritaire(s) à consolider
          </p>
        </div>

        <button
          onClick={() => setIsAddingItem(true)}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold rounded-md shadow-xs transition-colors shrink-0"
        >
          <Plus className="w-3.5 h-3.5" />
          <span>Ajouter une demande d’info</span>
        </button>
      </div>

      {/* Progress & Status Card */}
      <div className="bg-white border border-slate-200 rounded-lg p-4 shadow-xs flex items-center justify-between text-xs">
        <div className="flex items-center gap-3">
          <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold ${
            unresolvedCount === 0 ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-800'
          }`}>
            {items.length - unresolvedCount}/{items.length}
          </div>
          <div>
            <div className="font-bold text-slate-900">
              {unresolvedCount === 0 ? 'Dossier entièrement sécurisé !' : `${unresolvedCount} information(s) manquante(s) identifiée(s)`}
            </div>
            <p className="text-slate-500 text-[11px]">
              {unresolvedCount === 0 
                ? 'Tous les points de blocage identifiés ont été renseignés avec succès.'
                : 'Posez ces questions précises à l’équipe technique pour prémunir l’entreprise contre un rejet d’audit.'}
            </p>
          </div>
        </div>

        <div className="text-right">
          <div className="text-[11px] text-slate-400">Taux de résolution</div>
          <div className="text-sm font-bold text-slate-800 tabular-nums">
            {items.length > 0 ? Math.round(((items.length - unresolvedCount) / items.length) * 100) : 100}%
          </div>
        </div>
      </div>

      {/* Missing Information Cards */}
      <div className="space-y-4">
        {items.map((item) => (
          <div
            key={item.id}
            className={`bg-white border rounded-lg p-5 shadow-xs transition-all ${
              item.resolved
                ? 'border-emerald-200 bg-emerald-50/20 opacity-75'
                : 'border-slate-200 hover:border-slate-300'
            }`}
          >
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-start gap-3">
                <input
                  type="checkbox"
                  checked={item.resolved}
                  onChange={() => toggleResolved(item.id)}
                  className="mt-1 rounded text-emerald-600 focus:ring-emerald-500 w-4 h-4 cursor-pointer"
                  id={`check-${item.id}`}
                />
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    {getCategoryBadge(item.category)}
                    <label htmlFor={`check-${item.id}`} className={`text-sm font-bold cursor-pointer ${
                      item.resolved ? 'line-through text-slate-500' : 'text-slate-900'
                    }`}>
                      {item.title}
                    </label>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    {item.description}
                  </p>
                </div>
              </div>

              <div className="shrink-0">
                <span className={`text-[11px] font-semibold px-2 py-0.5 rounded ${
                  item.resolved
                    ? 'text-emerald-700 bg-emerald-100'
                    : 'text-amber-800 bg-amber-100'
                }`}>
                  {item.resolved ? 'Résolu' : 'À collecter'}
                </span>
              </div>
            </div>

            {/* Impact & Question Box */}
            <div className="mt-4 pt-3 border-t border-slate-100 grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
              <div className="bg-red-50/50 border border-red-100 rounded p-3 space-y-1">
                <div className="font-semibold text-red-900 text-[11px] flex items-center gap-1">
                  <AlertTriangle className="w-3.5 h-3.5 text-red-600" />
                  Risque en cas de contrôle MESR / Fiscal
                </div>
                <p className="text-red-950 text-[11px] leading-relaxed">
                  {item.impactOnAudit}
                </p>
              </div>

              <div className="bg-blue-50/50 border border-blue-100 rounded p-3 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-semibold text-blue-900 text-[11px] flex items-center gap-1">
                    <MessageSquare className="w-3.5 h-3.5 text-blue-600" />
                    Question à poser à l’équipe technique
                  </span>
                  <button
                    onClick={() => handleCopyQuestion(item.id, item.recommendedQuestion)}
                    className="text-[10px] text-blue-700 hover:text-blue-900 font-semibold underline flex items-center gap-1"
                  >
                    {copiedId === item.id ? 'Copié !' : 'Copier'}
                  </button>
                </div>
                <p className="text-blue-950 text-[11px] italic bg-white/70 p-2 rounded border border-blue-100">
                  « {item.recommendedQuestion} »
                </p>
                <div className="text-[10px] text-slate-500">
                  <strong>Livrable attendu :</strong> {item.expectedDeliverable}
                </div>
              </div>
            </div>
          </div>
        ))}

        {items.length === 0 && (
          <div className="bg-white border border-slate-200 rounded-lg p-10 text-center text-xs text-slate-500">
            <CheckCircle2 className="w-8 h-8 text-emerald-500 mx-auto mb-2" />
            Aucun manque d’information critique détecté pour ce projet. Le dossier paraît solide.
          </div>
        )}
      </div>

      {/* Modal to add custom missing information */}
      {isAddingItem && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg shadow-xl border border-slate-200 max-w-lg w-full p-6 space-y-4">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <h3 className="text-sm font-bold text-slate-900">
                Ajouter une demande de renseignement
              </h3>
              <button
                onClick={() => setIsAddingItem(false)}
                className="text-slate-400 hover:text-slate-600 text-sm"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleAddNewItem} className="space-y-3.5 text-xs">
              <div>
                <label className="block font-medium text-slate-700 mb-1">Intitulé du manque *</label>
                <input
                  type="text"
                  required
                  value={newItemTitle}
                  onChange={(e) => setNewItemTitle(e.target.value)}
                  placeholder="Ex : Justification de l’antériorité de l’algorithme"
                  className="w-full px-3 py-2 border border-slate-300 rounded-md focus:border-blue-500 focus:outline-hidden"
                />
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">Catégorie *</label>
                <select
                  value={newItemCategory}
                  onChange={(e) => setNewItemCategory(e.target.value as any)}
                  className="w-full px-3 py-2 border border-slate-300 rounded-md focus:border-blue-500 focus:outline-hidden"
                >
                  <option value="ETAT_DE_LART">État de l’art (bibliographie, brevets)</option>
                  <option value="VERROU">Verrou technique ou scientifique</option>
                  <option value="EXPERIMENTATION">Expérimentation & Itérations d’échec</option>
                  <option value="RESULTATS">Résultats quantitatifs & métriques</option>
                  <option value="PERSONNEL">Personnel & Feuilles de temps (CRA)</option>
                  <option value="CII_MARCHE">Marché pertinent & Comparatif CII</option>
                </select>
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">Question recommandée pour le client</label>
                <textarea
                  rows={2}
                  value={newItemQuestion}
                  onChange={(e) => setNewItemQuestion(e.target.value)}
                  placeholder="Formulez la question précise à adresser à l’ingénieur..."
                  className="w-full px-3 py-2 border border-slate-300 rounded-md focus:border-blue-500 focus:outline-hidden"
                />
              </div>

              <div>
                <label className="block font-medium text-slate-700 mb-1">Pièce / Livrable attendu</label>
                <input
                  type="text"
                  value={newItemDeliverable}
                  onChange={(e) => setNewItemDeliverable(e.target.value)}
                  placeholder="Ex : Rapport de benchmark .pdf daté d’avant les travaux"
                  className="w-full px-3 py-2 border border-slate-300 rounded-md focus:border-blue-500 focus:outline-hidden"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setIsAddingItem(false)}
                  className="px-3 py-1.5 text-slate-600 hover:text-slate-800 font-medium"
                >
                  Annuler
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-md shadow-xs"
                >
                  Ajouter au dossier
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
